<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicamentosMozPhamrmaLDAListTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('medicamentos')->insert([
            ['nome' => 'AMOXICILINA + AC. CLAVULÂNICO BASI', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMOXICILINA + AC. CLAVULÂNICO BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BALSAMO ANALGESICO BASI', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BRONCOSIL', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CARPLEXIL', 'designacao' => 'Creme Bisnaga', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CIPROFLOXACINA BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLARITROMICINA BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLOPIDOGREL BASI', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLOTRIMAZOL BASI 20G', 'designacao' => 'Creme Bisnaga', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLOTRIMAZOL BASI 20ML', 'designacao' => 'Solução cutânea', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLOTRIMAZOL BASI CREME VAGINAL', 'designacao' => 'Creme Bisnaga', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DAGESIL', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DESLORATADINA BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DIMIDON SUSP. ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DIMIDON', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DIMIDON', 'designacao' => 'Supositório', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCLOXACILINA BASI 250MG/5ML PO ORAL 100ML 1FR', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCLOXACILINA BASI 500MG 24CAPS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCONAZOL BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUMINOC 20+120 CP', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FUNGUR', 'designacao' => 'Creme Bisnaga', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FUNGUR', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLICERINA LACTENTE', 'designacao' => 'Supositório', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLICERINA INFANTIL', 'designacao' => 'Supositório', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IKYNOL', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LORATADINA BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LOSARTAN', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LOSARTAN BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'OMEPRASOL BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PARACETAMOL BASI 500', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PARACETAMOL BASI 1000', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PARKADINA', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PELITRIX 10MG/G CREME 15G 1UN', 'designacao' => 'Creme dermatológico', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PULDREN 2% 1FR', 'designacao' => 'Solução tópica', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PULDREN 4% 1FR', 'designacao' => 'Solução tópica', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ROXAZIN (ROSUVASTATINA) 5MG 56COMP', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ROXAZIN (ROSUVASTATINA) 10MG 56COMP', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'STRYMIX (PREGABALINA) 25MG 56CAPS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'STRYMIX (PREGABALINA) 50MG 56CAPS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'STRYMIX (PREGABALINA) 75MG 56CAPS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'STRYMIX (PREGABALINA) 150MG 56CAPS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'STRYMIX (PREGABALINA) 300MG 56CAPS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TANSULOSINA BASI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TANSULOSINA BASI', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TERBUL (TIOCONAZOL)', 'designacao' => 'Creme Bisnaga', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TIADIL', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TOMIN', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TOZEVITE XP', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'URTICUR SOL ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'URTICUR', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VASELINA GEL 20G BASI', 'designacao' => 'Gel Bisnaga', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VASELINA PURA BASI 30G', 'designacao' => 'Gel Bisnaga', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZARVITE', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZYXIUS (DIMETINDENO)1MG/G GEL 30G 1BISNAG', 'designacao' => 'Gel Bisnaga', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZYXIUS (DIMETINDENO)1MG/G GEL 50G 1BISNAG', 'designacao' => 'Gel Bisnaga', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'COMPLEXO B BASI', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE GOTAS ORAIS', 'designacao' => 'Gotas orais', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE CALCIO + D3', 'designacao' => 'Comprimidos efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE LIMAO 1000MG', 'designacao' => 'Comprimidos efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE MULTIVITAM+MINERAL', 'designacao' => 'Comprimidos efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE MULTIVITAMINAS KIDS', 'designacao' => 'Comprimidos efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE ZINCO + VITAMINAC + E', 'designacao' => 'Comprimidos efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE ENERGIA 60GOMAS', 'designacao' => 'Gomas', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE IMUNIDADE 60GOMAS', 'designacao' => 'Gomas', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CORVITE VITAMINA C 60GOMAS', 'designacao' => 'Gomas', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ENSER', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FERBASI DUO 15AMP+15CAPS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MULTIVITAMINAS BASI XP', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'REVIFORCE EXTRA SOL', 'designacao' => 'Ampola Bebível', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'REVIFORCE LIQUIDO (NOVA FORMULA)', 'designacao' => 'Solução líquida', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'REVIFORCE ADULTO', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ADRENALINA BASI 1MG/ML SOL INJ 1ML 10AMP', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AGUA PARA PREP INJ BASI 10ML 10AMP', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ANTADAR (CEFOTAXIMA)', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BESILATO DE ATRACÚRIO BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEFEPIMA BASI 1000MG PO P/SOL INJ OU PERF 10FR', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEFTAZIDIMA BASI 2G PO INJ 10FR', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLORETO DE POTASSIO BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DAGESIL (DICLOFENAC)', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DOPAMINA BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ENTIX INJECTAVEL', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FENTANILO BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROXOCOBALAMINA BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ISITRI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LEVOFLOXACINA BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METOCLOPRAMIDA BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METAMIZOL BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'NORADRENALINA BASI', 'designacao' => 'Ampola', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'OMEPRASOL BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PETIDINA BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PROMETAZINA BASI', 'designacao' => 'Injetável', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPOFEN (PARACETAMOL) 10MG/ML SOL PERF', 'designacao' => 'Solução oral perfumada', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRAMADOL BASI', 'designacao' => 'Ampola', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLUCOSE 5% BASI IV 500ML T.H. 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLUCOSE 5% BASI 1000ML T.H. 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLUCOSE 10% BASI 500ML DE 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLUCOSE 30% BASI 500ML DE 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLUCOSE 5%+CL SODIO 0,9% BASI 500ML DE 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'RINGER COM LACTACTO BASI 500ML 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'RINGER COM LACTACTO BASI 1000ML 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SOL POLIELECTROLIT C/GLUC BASI 500ML T.H. 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SOL POLIELECTROLITICA BASI 500ML T.H. 1FR', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CESOL CHAMPO', 'designacao' => 'Chapo', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GRISE CREME GORDO', 'designacao' => 'Creme', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GRISE CREME VITAMINADO', 'designacao' => 'Creme', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROLACT LEITE CORPORAL', 'designacao' => 'Leite corporal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROLACT CREME FACIAL', 'designacao' => 'Creme facial', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROLACT CREME HIDRATANTE CORPORAL', 'designacao' => 'Creme', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROLACT CREME MAOS', 'designacao' => 'Creme', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROLACT EMOLIENTE CORPORAL', 'designacao' => 'Emoliente corporal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROLACT GEL DE BANHO', 'designacao' => 'Gel de Banho', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROLACT GEL DE BANHO AVEIA+AMIDO MILHO', 'designacao' => 'Gel de Banho', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDROLACT POMADA', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SAVORIX CHAMPO FREQUENCIA', 'designacao' => 'Shapo', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SAVORIX T CHAMPO ESTADOS DESCAMATIVOS', 'designacao' => 'Shapo', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ADESIVO COMUM BETER-PLASTE PER', 'designacao' => 'Ligadura', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LIGADURA GESSADA AFRE 15CMX2,70CM 1UN', 'designacao' => 'Ligadura', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LIGADURA GESSADA AFRE 15CMX3CM 1UN', 'designacao' => 'Ligadura', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LIGADURA GESSADA ORTHOBAND 15CMX3M', 'designacao' => 'Ligadura', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LIGADURA GESSADA VENDARI POP 15CMX2,7CM', 'designacao' => 'Ligadura', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO AD TRANSP C/COMP CURAPOR', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ADES TNT C/COMP CURAPOR', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ADESIVO TRANSPARENTE FILPORO', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO TRANSP POREFIX MAIMED', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO CIRURGICO TNT C/COMP CIRPOR', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ADES TRANSP SUPRASORB F', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ESPUMA AD SUPRASORB P', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ESPUMA SUPRASORB P', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ALGINATO CA SUPRASORB A 10X10CM 10UN (20441)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ALGINATO DE CA SUPRASORB A 5X5CM 10UN (20440)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO DEBRISOFT PAD 10X10CM 5UN (34321)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO CARVAO+PRAT VLIWAKTIV AG 10X10CM 10UN (20701)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO HIDR SUPRASORB LIQUACEL 5X5CM 10UN (33435)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DEBRISOFT LOLLY 5UN (33224)', 'designacao' => 'Ligadura', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO HIDR SUPRASORB LIQUACEL 10X10CM 10UN (33436)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ALGINATO CA SUPRASORB A 30X2G 5UN (20445)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO SUPRASORB A+AG 5X5CM 10UN (20570)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO SUPERABSORVENTE VLIWASORB 10X10CM 10UN (24501)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO SUPRASORB X +PHMB 5X5CM 5UN (20540)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO SUPRASORB X +PHMB 9X9CM 5UN (20541)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO SUPRASORB LIQUACEL AG 10X10XM 10UN (142504)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO CARVAO+PRAT VLIWAKTIV AG 10X10CM 10UN (20705)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO CARVAO+PRAT VLIWAKTIV AG 10X20CM 10UN (20706)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO ALG+PRAT SUPRASORB A+AG 10X10CM 10UN (20571)', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PENSO SUPRASORB F 5X7CM 100UN', 'designacao' => 'Penso', 'unidade_medida' => 'cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
