<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicamentosObrisListTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    // Lista da Obris Pharma
    public function run()
    {
        DB::table('medicamentos')->insert([
            // Medicamentos anteriores...

            // Novos medicamentos
            ['nome' => 'BILOCOR 5', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BILOCOR 10', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CARVETREND 6,25', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CARVETREND 12,50', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CARVETREND 25', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CARZIN XL 4 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CREVAS 5 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CREVAS 10 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CREVAS 20 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNACAZ 60 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNACAZ 90 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNAFIL 50', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNAFIL 100', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNAFLOC 500', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNARB 150', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNARB 300', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EFFERFLU C', 'designacao' => 'Comprimidos Efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EFFERFLU  C IMUNE BOOSTER', 'designacao' => 'Comprimidos Efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EFFERFLU  C IMUNE BOOSTER PLUS', 'designacao' => 'Comprimidos Efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EFFERFLU  C IMUNE BOOSTER JUNIOR', 'designacao' => 'Comprimidos Efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ENAP 5', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ENAP 10', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ENAP 20', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ENAP CO', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FEDALOC 30', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FEDALOC 60', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'KEZ SHAMPOO', 'designacao' => 'Shampoo', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LISORETIC 10/12,50', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LISORETIC 20/12,50', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MEROJECT 500 MG', 'designacao' => 'Ampola', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MEROJECT 1 GR', 'designacao' => 'Injeção', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'NUBAN POMADA', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SIMVACOR 20', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SIMVACOR 40', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TAMOLTRA', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TEXA ALLERGY COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TEXA ALLERGY SYRUP', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TEXAMER 5 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRULOC IV 40 MG', 'designacao' => 'Ampolas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRYZETOR 10 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRYZETOR PLUS 10/10', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRYZETOR PLUS 10/20', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZYTOMIL 10 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZYTOMIL 20 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'POLLENTYME COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'POLLENTYME SUSPENSÃO ORAL', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'NODACIL', 'designacao' => 'Comprimido', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'NODAGAS', 'designacao' => 'Cápsulas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ORALDIET', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DENZIMAX', 'designacao' => 'Cápsulas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BROPULIN XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CRECIDIET APPÉTIT', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BROPUL GOTAS', 'designacao' => 'Gotas', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITALMAS MULTI', 'designacao' => 'Cápsulas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMLODIPINA TOLIFE 5 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMLODIPINA TOLIFE 10 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CETIRIZINA TOLIFE 10 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CIPROFLOXACINA TOLIFE 500', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCONAZOL TOLIFE 150 MG', 'designacao' => 'Cápsulas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LISINOPRIL 20 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LISINOPRIL 20 MG + HCTZ 12,5 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ACYCLOVIR DENK 200', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ACYCLOVIR CREME 5%', 'designacao' => 'Creme', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMOXI-DENK 1000', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMOXICLAV-DENK 1000/125', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMOXI-DENK 500', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMOXICLAV-DENK 500/62,50', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ANASTROZOLE 1 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ATENOLOL DENK 50 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CIPRO-DENK 500', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLOTRI-DENK 1% CREME', 'designacao' => 'Creme', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LEVO-DENK 500', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DOXI-DENK 100', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCONA-DENK 100', 'designacao' => 'Capsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCONA-DENK 150', 'designacao' => 'Capsulas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FURO-DENK 40', 'designacao' => 'Capsulas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GRANI-DENK 1 MG/ 1 ML', 'designacao' => 'Injetável', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IBU-DENK 600', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IMATINIB DENK 400 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LETROZOLE DENK 2,5 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LINOZOLID DENK 2MG/ML', 'designacao' => 'Injetável', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DENK-AIR 10', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DENK-AIR 4', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DENK-AIR 5', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ON.SETRON-DENK 4 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ON.SETRON-DENK 8 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PANTO-DENK 20', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PANTO-DENK 40', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PARA-DENK 125', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PARA-DENK 250', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DOLOFORTE DENK', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PARACETAMOL DENK 500 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PARACO-DENK 500/30 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ROSUVASTATIN DENK 10 mg', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ROSUVASTATIN DENK 20 mg', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ROSUVASTATIN DENK 5 mg', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRAMADOL DENK 50', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VORICONA-DENK 200', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZOLEDRO-DENK 4mg/5ml', 'designacao' => 'Ampola', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AGUA P/PREP INJECTÁVEIS 20 ML', 'designacao' => 'Ampolas', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BÁLSAMO ANALGÉSICO BASI POMADA', 'designacao' => 'Pomada', 'unidade_medida' => 'mg/g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BASIFLUX XAROPE 0,8 MG/ML(BROMEXINA)-FRS X 200 ML', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BASIFLUX XAR. 1,6 MG/ ML(BROMEXINA) - FRS X 200 ML', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BESCIL CREME VAGINAL', 'designacao' => 'Creme', 'unidade_medida' => 'mg/g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BETAMETASONA BASI POMADA', 'designacao' => 'Pomada', 'unidade_medida' => 'mg/g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BRONCOSIL (AMBROXOL)', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CARPLEXIL (HIDROCORTISONA) CREME', 'designacao' => 'Creme', 'unidade_medida' => 'mg/g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLARUS (DESLORATADINA) SOLUÇÃO', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLOTRIMAZOL BASI 1% CREME VAGINAL', 'designacao' => 'Creme Vaginal', 'unidade_medida' => 'mg/g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CLOTRMAZOL BASI 1% SOLUÇÃO CUTÂNEA', 'designacao' => 'Solução tópica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DABENZOL BASI SUSP. ORAL - FRS X 100 ML', 'designacao' => 'Suspensão líquida', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DABENZOL COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DAGESIL GEL', 'designacao' => 'Gel lubrificante', 'unidade_medida' => 'mg/g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DILACLAN (AMOXICILINA) 125 mg SUSPENSÃO', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DIMIDON SUSP. ORAL BASI', 'designacao' => 'Suspensão líquida', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ENSER (ÁCIDO FÓLICO)', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ENTIX 40 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EKISEM (NEOMICINA + BACITRACINA) POMADA', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FINATUX (CARBOCISTEÍNA) XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLICERINA SUPOSITÓRIOS ADULTO', 'designacao' => 'Supositório', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'INALGEX GEL', 'designacao' => 'Gel', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LOSARTAN 100 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METFORMINA 500 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METFORMINA 850 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METFORMINA 1000 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METOCLOPRAMIDA 5MG/ML SOL. INJECTÁVEL', 'designacao' => 'Injetável', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METRONIDAZOL 5 MG/ML', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MIDAZOLAM BASI 15 MG / 3 ML INJ', 'designacao' => 'Injetável', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MYMUS GOTAS', 'designacao' => 'Gotas', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'OMEPRAZOL BASI 20  MG', 'designacao' => 'Cápsulas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'OMEPRAZOL BASI 40 MG INJ', 'designacao' => 'Ampola', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PANTOPRAZOL BASI 40 MG INJ', 'designacao' => 'Ampola', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PROMETAZINA 0,1% XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'RINGER LACTATO ASSOCIAÇÃO', 'designacao' => 'Solução intravenosa', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SULTRIMIX 240 MG/5ML SUEPENSÃO', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPIDON SUSPENSÃO ORAL', 'designacao' => 'Suspensão líquida', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPOFEN (PARACETAMOL) XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPOFEN 500 (PARACETAMOL)', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TENIVERME (FLUBENDAZOL) 100 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TENIVERME (FLUBENDAZOL) SUSP. ORAL', 'designacao' => 'Suspensão líquida', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TOCELIV TOSSE SECA', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRIPLEXIL CREME', 'designacao' => 'Creme dental', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITASMA 2MG/5ML XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CIPSUN 500', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESOZOLE 20', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESOZOLE 40', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IBURISE-400', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LEVOSUN 500', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ORBIS PÁRA JÁ', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PERBITENOL 100', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PERBITENOL 50', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'RISEGRA 100', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'RISEGRA 50', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'RISOPINE 200', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUNFENAC 50', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUNMIDE 5', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRIPSUN 25', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZITHOSUN 500', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ACETONA PURA VELVET', 'designacao' => 'Higiene', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ACETONA SUAVIZADA VELVET', 'designacao' => 'Higiene', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÁGUA DE ROSAS VELVET', 'designacao' => 'Hidratante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÁGUA OXIGENADA 10 VOL VELVET', 'designacao' => 'Desinfetante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÁGUA OXIGENADA 20 VOL VELVET', 'designacao' => 'Desinfetante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ALCOOL ETÍLICO A 70 %', 'designacao' => 'Higiene', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ALCOOL ETÍLICO A 96 %', 'designacao' => 'Higiene', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ALERGRIP', 'designacao' => 'Antialérgico', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AZUL DE METILENO 0,1%', 'designacao' => 'Antisséptico e corante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AZUL DE METILENO 1%', 'designacao' => 'Antisséptico e corante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BICARBONATO DE SÓDIO', 'designacao' => 'Comprimido efervescente', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BOULACTIS PLUS', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'COMPLEXO B COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'COMPLEXO B FORTE COMP. EFERVESCENTES', 'designacao' => 'Comprimido efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'COMPLEXO B XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DIOSLEG FORTE', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DOLINAC COLÍRIO', 'designacao' => 'Colírio', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EOSINA SOLUTO 2%', 'designacao' => 'Solução', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FERBASI XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCLOXACICLINA 250MG75ML SUSPENSÃO ORAL', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCLOXACICLINA 500 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GYLDAZOL (METRONIDAZOL) 250 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDRARAPID', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IMUNAVIT', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IODOPOVIDONA SOLUÇÃO 10%', 'designacao' => 'Solução', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IODOPOVIDONA SPRAY 10%', 'designacao' => 'Spray', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MAGNETRIL D', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MANOCYTIS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MOLIRIN (AMOXICILINA) 500', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MOLIRIN (AMOXICILINA) 250 MG/5ML SUSPENSÃO', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MOVIPLUS ARTRO', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MYMUS GOTAS', 'designacao' => 'Gotas', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'NERILON COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÓLEO DE AMENDOAS DOCES', 'designacao' => 'Óleo', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÓLEO DE RÍCINO', 'designacao' => 'Óleo', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PERPHYL XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PROSEPTYL DOSEADOR', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PROSEPTYL SPRAY', 'designacao' => 'Spray', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'QUANTIVIT GOTAS', 'designacao' => 'Suplemento alimentar', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SEDANOCT', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SOLUTO DAKIN', 'designacao' => 'Solução', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SORO FISIOLÓGICO', 'designacao' => 'Solução', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPIDON SUSPENSÃO', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TAMARIFLUX', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TINTURA DE IODO', 'designacao' => 'Solução tópica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TOVYSIC COLÍRIO', 'designacao' => 'Colírio', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VASELINA PURIFICADA', 'designacao' => 'Pomada', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VASOTIL 10 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELTUSS ADULTO', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELTUSS CRIANÇA', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELTUSS CHUPA CHUPA MORANGO', 'designacao' => 'Pastilha', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELVET MATERNA', 'designacao' => 'Loção', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELVITA C 500 MG COMPRIMIDOS MASTIGÁVEIS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELVITA C COMPRIMIDOS EFERVESCENTES', 'designacao' => 'Comprimidos Efervescente', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELVITA C GOTAS', 'designacao' => 'Gotas', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELVITA C XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VELVITA D3', 'designacao' => 'solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VIOLETA GENCIANA', 'designacao' => 'Solução tópica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITANIUM KIDS XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITANIUM MULTIVIT COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZILANTIX 500 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZILANTIX (AZITROMICIBA SUSPENSÃO', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ADESIVO TEXTIL CARNE SALVELOX', 'designacao' => 'Curativo adesivo', 'unidade_medida' => 'm/cm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÁGUA ISOTÓNICA INFANTIL', 'designacao' => 'Solução hidratante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CHOLAXON CÁPSULAS', 'designacao' => 'Cápsulas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CHOLAXON GOTAS', 'designacao' => 'Gotas', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DIGERON', 'designacao' => 'Pastilhas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DROPSETAS LARANJA E MEL', 'designacao' => 'Gotas', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DROPSETAS LIMÃO E MEL', 'designacao' => 'Pastilhas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DROPSETAS MENTA E EUCALIPTO', 'designacao' => 'Pastilhas', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ISOMAR 2 EM 1', 'designacao' => 'Higiene', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ISOMAR OCCHI - SOLUÇÃO OFTÁLMICA', 'designacao' => 'Higiene', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MAGNÉSIO-FOS AMPOLAS BEBÍVEIS', 'designacao' => 'Ampolas Bebíveis', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MAGNÉSIO-FOS COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MOVITUM ACTIVE AMPOLAS BEBÍVEIS', 'designacao' => 'Ampolas Bebíveis', 'unidade_medida' => 'ampola', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MOVITUM MULTIVIT', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MOVITUM SENIOR +50', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SALVELOX SOLUÇÃO PARA LENTES DE CONTACTO', 'designacao' => 'Outro', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SEDOPAX NOITE', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ULTRADEX COLUTÓRIO', 'designacao' => 'higiene bucal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ULTRADEX DENTRÍFICO BAIXA ABRASIVIDADE', 'designacao' => 'Creme dental', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BIO OIL', 'designacao' => 'Loção', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LABBELLO CEREJA', 'designacao' => 'Bastão labial', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LABBELLO CLASSIC CARE', 'designacao' => 'Bastão labial', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LABBELLO HIDRO CARE', 'designacao' => 'Bastão labial', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LABBELLO MORANGO', 'designacao' => 'Bastão labial', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BOIÃO', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ISOVENT 200', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LUBRIFICANTE CLASSIC carteiras', 'designacao' => 'Gel lubrificante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LUBRIFICANTE CLASSIC GARRAFA', 'designacao' => 'Gel lubrificante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LUBRIFICANTE MORANGO carteiras', 'designacao' => 'Gel lubrificante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LUBRIFICANTE MORANGO GARRAFA', 'designacao' => 'Gel lubrificante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MICROLENYN', 'designacao' => 'Comprimido', 'unidade_medida' => 'kit', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PROGESTYN', 'designacao' => 'Comprimido', 'unidade_medida' => 'kit', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PRUDENCE MORANGO', 'designacao' => 'Preservativo', 'unidade_medida' => 'unidade', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PRUDENCE NICE', 'designacao' => 'Preservativo', 'unidade_medida' => 'unidade', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PRUDENCE SENSUAL DOTTED', 'designacao' => 'Preservativo', 'unidade_medida' => 'unidade', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SEGURO', 'designacao' => 'Kit de Aporto', 'unidade_medida' => 'kit', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'KIT TESTE PAPANICOLAU', 'designacao' => 'Kit Diagnóstico', 'unidade_medida' => 'unidade', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FURUNBAO', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ULCYLORI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
