<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicamentosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    //  Lista de Natur_Pharma
    public function run(): void
    {
        DB::table('medicamentos')->insert([
            ['nome' => 'AMOXICILINA 500 LABESFAL', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AZITROMICINA 500 MG LABESFAL', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEFITON LABESFAL COMPRIMIDOS 400 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEFITON LABESFAL SUSPENSÃO (CEFIXIMA)', 'designacao' => 'Suspensão oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DICLOFENAC 100 MG RETARD', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TRICALMA (IBUPROFENO LABESFAL) 400 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METOCLOPRAMIDA 10 MG LABESFAL', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ASCABIOL LOÇÃO', 'designacao' => 'Loção tópica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PHENERGAN 2% COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PHENERGAN 2% CREME', 'designacao' => 'Creme dermatológico', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PHENERGAN 0,1% XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TONIFER SYRUP', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'UROFAST (FOSFOMICINA) SOLUÇÃO ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZESTOQUINE FORTE', 'designacao' => 'Comprimido', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZEEFUSE 2%', 'designacao' => 'Comprimido', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EGREMA IODOPOVIDONA BUCAL 10%', 'designacao' => 'Solução Buca', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EGREMA IODOPOVIDONA VAGINAL 10%', 'designacao' => 'Pomada Vagina', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EGREMA, IODOPOVIDONA CHAMPÔ 7,5%', 'designacao' => 'Champô', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EGREMA, IODOPOVIDONA POMADA DÉRMICA 10%', 'designacao' => 'Pomada Dérmica', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EGREMA, IODOPOVIDONA SOL.VAGINAL 4% (ESPUMA)', 'designacao' => 'Espuma Vaginal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EGREMA, IODOPOVIDONA SOLUÇÃO DÉRMICA 10%', 'designacao' => 'Solução Dérmica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SAVICRUB CETRIMIDA + CLOROHEXIDINA', 'designacao' => 'Solução Antisséptica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SAVICRUB DIGLUCONATO CLOROHEXIDINA 4%', 'designacao' => 'Solução Antisséptica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÁLCOOL A 70%', 'designacao' => 'Solução Líquida', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÁLCOOL A 96%', 'designacao' => 'Solução Líquida', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TIMOX-SOLUÇÃO OFTÁLMICA (TIMOLOL)', 'designacao' => 'Solução Oftálmica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÁGUA OXIGENADA 3% 10 VOLUMES', 'designacao' => 'Solução Líquida', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÓLEO DE AMENDOAS DOCES', 'designacao' => 'Óleo', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TINTURA DE IODO', 'designacao' => 'Solução Alcoólica', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FURUNBAO', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'C-VIT RADIANCE FLUIDO LUMINOSO', 'designacao' => 'Sérum', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SEBOVALIS GEL FACIAL', 'designacao' => 'Gel', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SEBOVALIS CLASSIC CHAMPO ANTI-CASPA', 'designacao' => 'Champô', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITISES GEL PIGMENTANTE', 'designacao' => 'Gel', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CICASES WH CREME EPITALIZANTE', 'designacao' => 'Creme', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BE YOUNG SERUM SOPHIE', 'designacao' => 'Sérum', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BE YOUNG CONTORNO DE OLHOS SOPHIE', 'designacao' => 'Creme', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GEL LIMPEZA OIL STOP SOPHISKIN', 'designacao' => 'Gel', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SERUM OIL STOP PONTOS NEGROS', 'designacao' => 'Sérum', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MASK OIL STOP SOPHIE', 'designacao' => 'Máscara', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SERUM HYDRABOOST ANTIRUGAS', 'designacao' => 'Sérum', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CREME NOITE HIDRABOOST SOPHIE', 'designacao' => 'Creme', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CELULEX GEL ANTICELULÍTICO', 'designacao' => 'Gel', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESTRYSES LOÇÃO ANTIESTRIAS', 'designacao' => 'Loção', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESTRYSES SERUM FORTE ANTIESTRIAS', 'designacao' => 'Sérum', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'HIDRADERMIN BODY MILK (HIDRATANTE)', 'designacao' => 'Leite hidratante', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE BALSAMO LABIAL LSF 30', 'designacao' => 'Bálsamo labial', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE BALSAMO LABIAL SIMPLES', 'designacao' => 'Bálsamo labial', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE CICADERME CREME', 'designacao' => 'Creme', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE CICADERME POMADA', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE CREME DE MAOS', 'designacao' => 'Creme', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE CREME EMOLIENTE', 'designacao' => 'Creme', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE CREME GORDO', 'designacao' => 'Creme', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE ESCALDERME', 'designacao' => 'Creme', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE GEL CREMOSO', 'designacao' => 'Gel', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE GEL DE BANHO', 'designacao' => 'Gel', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE PRURIDERME BANHO', 'designacao' => 'Sabonete líquido', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE PRURIDERME CREME', 'designacao' => 'Creme', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE PRURIDERME GEL', 'designacao' => 'Gel', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LADVANCE SABONETE LÍQUIDO', 'designacao' => 'Sabonete líquido', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPLIME COMPLEXO B COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPLIME COMPLEXO B KIDS', 'designacao' => 'Comprimido mastigável', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPLIME POLIVITAMÍNICO E MINERAL KIDS', 'designacao' => 'Comprimido mastigável', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPLIME MATERN', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPLIME COF KIDS', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPLIME COF ADULTO', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'METROLE 500', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PREDOL-5', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PREDOL-10', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PREDOL-20', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYCOTRA SUSPENSION', 'designacao' => 'Suspensão', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYLUCID SUSPENSAO', 'designacao' => 'Suspensão', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNCLOPEN PLUS-EC', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYNTOX-DS 125 MG SUSPENSÃO', 'designacao' => 'Suspensão', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYTRIPTIN 25 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYUNFEN-P SUSPENSÃO', 'designacao' => 'Suspensão', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYVORM-200 SUSPENSION', 'designacao' => 'Suspensão', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYVORM-400 COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DYZEPIN 200 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'LORCARE SUSPENSÃO (LORATADINA)', 'designacao' => 'Suspensão', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITOLDYN-L', 'designacao' => 'Suplemento vitamínico', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITOLDYN-P', 'designacao' => 'Suplemento vitamínico', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZAPCOLD SYRUP', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZINGMOL 500 COMPRIMIDOS', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ZINGMOL SUSPENSION PLUS', 'designacao' => 'Suspensão', 'unidade_medida' => 'mg/ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMLODIPINA 10 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AMLODIPINA 5 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BRAITER 20 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BRAITER 40 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BRONCOLIBER ADULTO', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BRONCOLIBER infantil', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CIPROFLOXACINA FARMOZ 500 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DILTIAZEM 180 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCONAZOL SUPREMASE 150 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLUCONAZOL SUPREMASE 200 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IMPRUVE 5 MG (FINASTERIDE)', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MAGNESIOCARD (MAGNÉSIO)', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MIRTAZAPINA FARMOZ 15 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MIRTAZAPINA FARMOZ 30 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PAROXETINA FARMOZ 20 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'RELIVA TANSULOSINA 0,4 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'TERBINAFINA 250 MG', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITAMINA C + ZINCO + VITAMINA B6', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CANDICORT CRÈME', 'designacao' => 'Creme', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CANDICORT POMADA', 'designacao' => 'Pomada', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DECADRON NASAL', 'designacao' => 'Spray nasal', 'unidade_medida' => 'mcg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FLAGASS GOTAS', 'designacao' => 'Gotas', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PREDNISOLONA SOLUÇÃO ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ARTRONAT RAPID', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM ENERGY', 'designacao' => 'Ampolas bebíveis', 'unidade_medida' => 'mk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM FORTE + GINKGO BILOBA', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM FORTE + GINKGO BILOBA', 'designacao' => 'Ampolas bebíveis', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM FORTE SHOT (EFEITO IMEDIATO)', 'designacao' => 'Ampolas bebíveis', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM FORTE COM CEROSOMAS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM FORTE COM CEROSOMAS', 'designacao' => 'Ampolas bebíveis', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM GOLD 50+', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM GOLD 50+', 'designacao' => 'Ampolas bebíveis', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM MINI KIDS', 'designacao' => 'Ampolas bebíveis', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM MULTIVITAMINAS E SAIS MINERAIS DE A-Z', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CEREBRUM STUDENT', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CHÁ TRIFAST TG', 'designacao' => 'Chá', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CURCUMIDO COMPLEX', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GINKGO FORTE CÁPSULAS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GINKGO FORTE ampolas bebiveis', 'designacao' => 'Ampolas bebíveis', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MAGNÉSIO ADVANCED', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GMET MELATONAT FORTE', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SUPERNAT - OMEGA 3 1000 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ADOÇANTE EDULCOR', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'EUTAVOS K2', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'VITAMINA E', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BABA DE CARACOL CREME', 'designacao' => 'Creme dermatológico', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ADELGACELL CELULITE', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ALHO 1000 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'BACIDOPHILUS', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CÁLCIO + MAGNÉSIO + ZINCO + VITAMINA D', 'designacao' => 'Comprimido', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CARVÃO VEGETAL', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DRENALIGHT BARRIGA PLANA - SOLUÇÃO ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DRENALIGHT DETOX - SOLUÇÃO ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DRENALIGHT GOLDEN DEPUR - SOLUÇÃO ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DRENALIGHT HOT - SOLUÇÃO ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'DRENALIGHT HYDRA SOLUÇÃO ORAL', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GASTROMIL PASTILHAS', 'designacao' => 'Pastilha', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GINEX ÍNTIMO', 'designacao' => 'Sabonete líquido', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLUCOSAMINA + CONDROITINA', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'IMUNID', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MORINGA OLEFEIRA CAPS 30+ 30', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'MORINGA OLEIFEIRA XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'NUTRIKINGS APETITE SOLUÇÃO', 'designacao' => 'Solução oral', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÓLEO FÍGADO DE BACALHAU 1000 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÓLEO FÍGADO DE BACALHAU 400 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ÓLEO FÍGADO DE BACALHAU PLUS XAROPE', 'designacao' => 'Xarope', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'OMEGA 3 1000 MG', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'OMEGA 3/6/9', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PHITOPAUSA', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PROSTANATUR', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SABONETE DE GLICERINA (GLYCERPIL)', 'designacao' => 'Sabonete', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ULCYLORI', 'designacao' => 'Cápsula', 'unidade_medida' => 'mg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'AQUEOS CREAM NEUTRO', 'designacao' => 'Creme dermatológico', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLYCERINE PLUS NATURAL TRANSPARENTE', 'designacao' => 'Sabonete', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLYCERINE PLUS NATURAL VERMELHO', 'designacao' => 'Sabonete', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLYCERINE PLUS NATURAL AMARELO', 'designacao' => 'Sabonete', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GLYCERINE PLUS NATURAL VERDE', 'designacao' => 'Sabonete', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SWOT CREAM REPELENTE', 'designacao' => 'Creme repelente', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CERA ORTODONTICA PIERROT', 'designacao' => 'Cera ortodôntica', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CREME DENTÁRIO PIERROT BRANQUEADOR', 'designacao' => 'Creme dentário', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CREME DENTÁRIO PIERROT PROPOLIS', 'designacao' => 'Creme dentário', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CREME DENTÍFRICO PIERROT-DENTES SENSÍVEIS', 'designacao' => 'Creme dentário', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'CREME DENTÍFRICO PIERROT-FRESCURA NATURAL', 'designacao' => 'Creme dentário', 'unidade_medida' => 'g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA ELÉCTRICA PIERROT', 'designacao' => 'Dispositivo elétrico', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA INFANTIL PIERROT BABY', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA INFANTIL PIERROT CHISPA', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA INFANTIL PIERROT GUSY', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA INFANTIL PIERROT JÚNIOR', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA INFANTIL PIERROT MONSTER', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA INFANTIL PIERROT PIWY', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT ACTION TIP MÉDIO', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT ACTION TIP SUAVE', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT B-ELLE', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT BLACK / WHITE', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT CLINIC SENSITIVE', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT MASSAGEM 45 MÉDIO', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT MASSAGEM 45 SUAVE', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT NEW ACTIVE DURA', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT NEW BALANCE TIP DURO', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT NEW BALANCE TIP MÉDIA', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT NEW BALANCE TIP SUAVE', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT SPECIALIST - ORTODONCIA', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVA PIERROT SPECIALIST-PÓS CIRÚRGICO', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVILHÃO INTERDENTAL CÓNICO SUAVE', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVILHÃO INTERDENTAL FINO SUAVE', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESCOVILHÃO INTERDENTAL MICRO', 'designacao' => 'Escova dental', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESTOJO VIAGEM PIERROT CLASSIC', 'designacao' => 'Kit de higiene bucal', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ESTOJO PIERROT KIT COMPLETO', 'designacao' => 'Kit de higiene bucal', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FITA DENTAL PIERROT', 'designacao' => 'Fita dental', 'unidade_medida' => 'm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FIO DENTAL PIERROT - EXPANSIVO', 'designacao' => 'Fio', 'unidade_medida' => 'm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'FIO DENTAL PIERROT ALOE VERA', 'designacao' => 'Fio', 'unidade_medida' => 'm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GEL DENTAL INFANTIL PIRROT - MORANGO', 'designacao' => 'Creme dentário', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GEL DENTAL PIERROT MICROPARTÍCULAS', 'designacao' => 'Creme dentário', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'GEL DENTAL PIERROT SHARKY APPLE', 'designacao' => 'Creme dentário', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PASTA DENTÍFRICA ANTI-PLACA', 'designacao' => 'Creme dentário', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PASTA DENTÍFRICA PIERROT 2 EM 1', 'designacao' => 'Creme dentário', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PASTA DENTÍFRICA PIERROT BRANQUEADORA 2 EM 1', 'designacao' => 'Creme dentário', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PASTA DENTÍFRICA PIERROT WHITENING', 'designacao' => 'Creme dentário', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PASTA DENTÍFRICA PIERROT CHARCOAL', 'designacao' => 'Creme dentário', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'PIERROT KIT ORTODONCIA', 'designacao' => 'Kit ortodôntico', 'unidade_medida' => 'unid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'SPRAY BUCAL PIERROT', 'designacao' => 'Spray bucal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ELIXIR PIERROT ANTI-PLACA', 'designacao' => 'Enxaguante bucal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ELIXIR PIERROT CLOROHEXIDINA', 'designacao' => 'Enxaguante bucal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ELIXIR PIERROT TOTAL CARE', 'designacao' => 'Enxaguante bucal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nome' => 'ELIXIR PIERROT WHITENING', 'designacao' => 'Enxaguante bucal', 'unidade_medida' => 'ml', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
